// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3VUGCTa3g-UFyluBgN62nX9_TWWJGzkI',
    appId: '1:670358895729:web:e5776ed22b6a3b4c07afd0',
    messagingSenderId: '670358895729',
    projectId: 'fooddeliveryapp-f6559',
    authDomain: 'fooddeliveryapp-f6559.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-f6559.appspot.com',
    measurementId: 'G-3NGN6F18T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB10JkIhN0MMZ57Y7WUwa03xp9W0TAhHKk',
    appId: '1:670358895729:android:8577a56436826cd007afd0',
    messagingSenderId: '670358895729',
    projectId: 'fooddeliveryapp-f6559',
    storageBucket: 'fooddeliveryapp-f6559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTHdJNd9SpEzc95Ga3-jGhkJBEAYJjGAw',
    appId: '1:670358895729:ios:f418832a81a0165907afd0',
    messagingSenderId: '670358895729',
    projectId: 'fooddeliveryapp-f6559',
    storageBucket: 'fooddeliveryapp-f6559.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTHdJNd9SpEzc95Ga3-jGhkJBEAYJjGAw',
    appId: '1:670358895729:ios:f418832a81a0165907afd0',
    messagingSenderId: '670358895729',
    projectId: 'fooddeliveryapp-f6559',
    storageBucket: 'fooddeliveryapp-f6559.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3VUGCTa3g-UFyluBgN62nX9_TWWJGzkI',
    appId: '1:670358895729:web:7b5eceb75242d2a707afd0',
    messagingSenderId: '670358895729',
    projectId: 'fooddeliveryapp-f6559',
    authDomain: 'fooddeliveryapp-f6559.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-f6559.appspot.com',
    measurementId: 'G-PPVJHWM2DQ',
  );
}
